// client/angular/src/app/components/add-book/add-book.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'apl-add-book',
  standalone: true,
  imports: [],
  templateUrl: './add-book.component.html',
  styleUrl: './add-book.component.scss',
})
export class AddBookComponent {}

<form class="add-book"[formGroup]="form" (submit)="handleSubmit()">
    @if (addBookSignal && addBookSignal().loading) {
        <p>Adding a new book...</p>
    }
    <fieldset class="field">
        <label for="name">Book name:</label>
        <input autocomplete="off" id="name" formControlName="name" type="text">
        @if (validator.errors('name')) {
            <p>{{validator.errors('name')}}</p>
        }
    </fieldset>
    <fieldset class="field">
        <label for="genre">Genre:</label>
        <input autocomplete="off" id="genre" formControlName="genre" type="text">
        @if (validator.errors('genre')) {
            <p>{{validator.errors('genre')}}</p>
        }
    </fieldset>
    <fieldset class="field">
        <label for="authorId">Author:</label>
        <select id="authorId" formControlName="authorId">
            <option value="" selected disabled>Select author</option>
            @if (authors().loading) {
                <option disabled>Loading authors...</option>
            } @else if (authors().error) {
                <option disabled>Error: {{authors().error}}</option>
            } @else {
                @for (author of authors().data?.authors; track $index) {
                    <option value="{{author.id}}">{{author.name}}</option>
                }
            }
        </select>
        @if (validator.errors('authorId')) {
            <p>{{validator.errors('authorId')}}</p>
        }
    </fieldset>
    <button type="submit">+</button>
</form>

// client/src/components/AddBook/AddBook.tsx
import { useQuery, useMutation } from "@apollo/client";
import {
  GET_AUTHORS,
  ADD_BOOK,
  type Author,
  type AddBookForm,
} from "./AddBook.queries";
import { GET_BOOKS } from "../BookList/BookList.queries";
import { useState } from "react";
import { addBookSchema } from "../../utils/yup";
import { resetForm } from "../../utils/reset";
import { useDispatch } from "react-redux";
import { addBook } from "../../store/bookSlice";

function AddBook() {
  const { loading, error, data } = useQuery(GET_AUTHORS);
  const [form, setForm] = useState<AddBookForm>({
    name: "",
    genre: "",
    authorId: "",
  });
  const [mutateFunction, { data: book, loading: adding, error: adderror }] =
    useMutation(ADD_BOOK, {
      refetchQueries: [{ query: GET_BOOKS }],
    });
  const dispatch = useDispatch();

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    const { id, value } = e.target;
    setForm({
      ...form,
      [id]: value,
    });
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    await addBookSchema
      .validate(form)
      .then((data) => {
        console.log(data);
        mutateFunction({ variables: form }).then(() => {
          dispatch(addBook(book));
          resetForm(form, setForm);
        });
      })
      .catch((e) => {
        console.error(e);
      });
  };

  return (
    <form id="add-book" onSubmit={handleSubmit}>
      {adderror && <p>{adderror.message}</p>}
      {adding && <p>Adding book</p>}
      <fieldset className="field">
        <label htmlFor="name">Book name:</label>
        <input
          type="text"
          id="name"
          value={form.name}
          onChange={handleChange}
        />
      </fieldset>
      <fieldset className="field">
        <label htmlFor="genre">Genre:</label>
        <input
          type="text"
          id="genre"
          value={form.genre}
          onChange={handleChange}
        />
      </fieldset>
      <fieldset className="field">
        <label htmlFor="authorId">Author:</label>
        <select id="authorId" value={form.authorId} onChange={handleChange}>
          <option value="">Select author</option>
          {loading && <option disabled>Loading authors...</option>}
          {error && <option disabled>Error loading authors</option>}
          {data &&
            data.authors.map((author: Author) => (
              <option key={author.id} value={author.id}>
                {author.name}
              </option>
            ))}
        </select>
      </fieldset>
      <button type="submit">+</button>
    </form>
  );
}

export default AddBook;
